description:
  This section describes all of the services that may be present on the AP.
  Each service is then referenced via its name inside an interface, ...
type: object
properties:
  lldp:
    $ref: "https://ucentral.io/schema/v1/service/lldp/"
  ssh:
    $ref: "https://ucentral.io/schema/v1/service/ssh/"
  ntp:
    $ref: "https://ucentral.io/schema/v1/service/ntp/"
  mdns:
    $ref: "https://ucentral.io/schema/v1/service/mdns/"
  rtty:
    $ref: "https://ucentral.io/schema/v1/service/rtty/"
  log:
    $ref: "https://ucentral.io/schema/v1/service/log/"
  http:
    $ref: "https://ucentral.io/schema/v1/service/http/"
  igmp:
    $ref: "https://ucentral.io/schema/v1/service/igmp/"
  radius-proxy:
    $ref: "https://ucentral.io/schema/v1/service/radius-proxy/"
  online-check:
    $ref: "https://ucentral.io/schema/v1/service/online-check/"
  data-plane:
    $ref: "https://ucentral.io/schema/v1/service/data-plane/"
  quality-of-service:
    $ref: "https://ucentral.io/schema/v1/service/quality-of-service/"
  wireguard-overlay:
    $ref: 'https://ucentral.io/schema/v1/service/wireguard-overlay/'
  gps:
    $ref: 'https://ucentral.io/schema/v1/service/gps/'
  telnet:
    $ref: "https://ucentral.io/schema/v1/service/telnet/"
  https:
    $ref: "https://ucentral.io/schema/v1/service/https/"
